url: https://ratzkeandassociatesltd.github.io
baseurl:

# Site settings
title: Ratzke & Associates Ltd.
email: info@ratzke.org
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1B482D
  secondary: 5A1717
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line:
  - line: Edmonton, Alberta

# Build settings
markdown: kramdown
permalink: pretty
